<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLvKHbzd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLvKHbzd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLvKHbzd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLvKHbzd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLvKHbzd\App_KernelDevDebugContainer([
    'container.build_hash' => 'LvKHbzd',
    'container.build_id' => '29f7a266',
    'container.build_time' => 1631512964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLvKHbzd');
