<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYuqPQu9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYuqPQu9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYuqPQu9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYuqPQu9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYuqPQu9\App_KernelDevDebugContainer([
    'container.build_hash' => 'YuqPQu9',
    'container.build_id' => '0c3f77b5',
    'container.build_time' => 1631588473,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYuqPQu9');
