<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCSk8pDJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCSk8pDJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCSk8pDJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCSk8pDJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCSk8pDJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'CSk8pDJ',
    'container.build_id' => 'b1744fc5',
    'container.build_time' => 1631580068,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCSk8pDJ');
