<?php

namespace ContainerYuqPQu9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PILHgu_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pILHgu.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pILHgu.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cableRepository' => ['privates', 'App\\Repository\\CableRepository', 'getCableRepositoryService', true],
        ], [
            'cableRepository' => 'App\\Repository\\CableRepository',
        ]);
    }
}
