<?php

namespace ContainerYuqPQu9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1CBPRyuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1CBPRyu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1CBPRyu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movement' => ['privates', '.errored..service_locator.1CBPRyu.App\\Entity\\Movement', NULL, 'Cannot autowire service ".service_locator.1CBPRyu": it references class "App\\Entity\\Movement" but no such service exists.'],
        ], [
            'movement' => 'App\\Entity\\Movement',
        ]);
    }
}
