<?php

namespace ContainerYuqPQu9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterialService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qDq33a1.App\Entity\Material' shared service.
     *
     * @return \App\Entity\Material
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qDq33a1": it references class "App\\Entity\\Material" but no such service exists.');
    }
}
