<?php

namespace ContainerYuqPQu9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskAddProjectTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TaskAddProjectType' shared autowired service.
     *
     * @return \App\Form\TaskAddProjectType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TaskAddProjectType.php';

        return $container->privates['App\\Form\\TaskAddProjectType'] = new \App\Form\TaskAddProjectType();
    }
}
