<?php

namespace ContainerLvKHbzd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RUkSBevService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RUkSBev' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RUkSBev'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projectCloseRepository' => ['privates', 'App\\Repository\\ProjectCloseRepository', 'getProjectCloseRepositoryService', true],
        ], [
            'projectCloseRepository' => 'App\\Repository\\ProjectCloseRepository',
        ]);
    }
}
