<?php

namespace ContainerRB5zbmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WTlUxUHService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.WTlUxUH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WTlUxUH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'project' => ['privates', '.errored..service_locator.WTlUxUH.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.WTlUxUH": it references class "App\\Entity\\Project" but no such service exists.'],
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
        ], [
            'project' => 'App\\Entity\\Project',
            'projectRepository' => 'App\\Repository\\ProjectRepository',
        ]);
    }
}
