<?php

namespace ContainerRB5zbmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ByglfufService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.byglfuf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.byglfuf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'toolRepository' => ['privates', 'App\\Repository\\ToolRepository', 'getToolRepositoryService', true],
        ], [
            'toolRepository' => 'App\\Repository\\ToolRepository',
        ]);
    }
}
