<?php

namespace ContainerRB5zbmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SWhx1raService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.SWhx1ra' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SWhx1ra'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cable' => ['privates', '.errored..service_locator.SWhx1ra.App\\Entity\\Cable', NULL, 'Cannot autowire service ".service_locator.SWhx1ra": it references class "App\\Entity\\Cable" but no such service exists.'],
        ], [
            'cable' => 'App\\Entity\\Cable',
        ]);
    }
}
