<?php

namespace ContainerRB5zbmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NXGxS3sService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.NXGxS3s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NXGxS3s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projectClose' => ['privates', '.errored..service_locator.NXGxS3s.App\\Entity\\ProjectClose', NULL, 'Cannot autowire service ".service_locator.NXGxS3s": it references class "App\\Entity\\ProjectClose" but no such service exists.'],
        ], [
            'projectClose' => 'App\\Entity\\ProjectClose',
        ]);
    }
}
