<?php

namespace ContainerRB5zbmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddProjectControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AddProjectController' shared autowired service.
     *
     * @return \App\Controller\AddProjectController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AddProjectController'] = $instance = new \App\Controller\AddProjectController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\AddProjectController', $container));

        return $instance;
    }
}
