<?php

namespace ContainerRB5zbmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCableControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CableController' shared autowired service.
     *
     * @return \App\Controller\CableController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CableController'] = $instance = new \App\Controller\CableController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\CableController', $container));

        return $instance;
    }
}
