<?php

namespace ContainerRB5zbmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ToolRepository' shared autowired service.
     *
     * @return \App\Repository\ToolRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ToolRepository'] = new \App\Repository\ToolRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
