<?php

namespace ContainerRB5zbmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ToolType' shared autowired service.
     *
     * @return \App\Form\ToolType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ToolType'] = new \App\Form\ToolType();
    }
}
