<?php

namespace ContainerE52Ow6G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QDq33a1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qDq33a1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qDq33a1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'material' => ['privates', '.errored..service_locator.qDq33a1.App\\Entity\\Material', NULL, 'Cannot autowire service ".service_locator.qDq33a1": it references class "App\\Entity\\Material" but no such service exists.'],
        ], [
            'material' => 'App\\Entity\\Material',
        ]);
    }
}
