<?php

namespace ContainerE52Ow6G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FsKfvx_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FsKfvx.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FsKfvx.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movementRepository' => ['privates', 'App\\Repository\\MovementRepository', 'getMovementRepositoryService', true],
        ], [
            'movementRepository' => 'App\\Repository\\MovementRepository',
        ]);
    }
}
