<?php

namespace ContainerE52Ow6G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SWhx1ra.App\Entity\Cable' shared service.
     *
     * @return \App\Entity\Cable
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SWhx1ra": it references class "App\\Entity\\Cable" but no such service exists.');
    }
}
