<?php

namespace ContainerE52Ow6G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovementTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MovementType' shared autowired service.
     *
     * @return \App\Form\MovementType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MovementType.php';

        return $container->privates['App\\Form\\MovementType'] = new \App\Form\MovementType();
    }
}
