<?php

namespace ContainerE52Ow6G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectCloseTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ProjectCloseType' shared autowired service.
     *
     * @return \App\Form\ProjectCloseType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProjectCloseType.php';

        return $container->privates['App\\Form\\ProjectCloseType'] = new \App\Form\ProjectCloseType();
    }
}
