<?php

namespace ContainerE52Ow6G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Vh2kqFh.App\Entity\Tool' shared service.
     *
     * @return \App\Entity\Tool
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Vh2kqFh": it references class "App\\Entity\\Tool" but no such service exists.');
    }
}
