<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRB5zbmO\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRB5zbmO/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRB5zbmO.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRB5zbmO\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRB5zbmO\App_KernelProdContainer([
    'container.build_hash' => 'RB5zbmO',
    'container.build_id' => 'e205f73a',
    'container.build_time' => 1631588520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRB5zbmO');
