<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAP7Zliw\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAP7Zliw/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAP7Zliw.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAP7Zliw\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAP7Zliw\App_KernelProdContainer([
    'container.build_hash' => 'AP7Zliw',
    'container.build_id' => '7b3736c0',
    'container.build_time' => 1631580175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAP7Zliw');
