<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Project extends \App\Entity\Project implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'contractNumber', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'registrationDate', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'startDate', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'endTime', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'advances', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'totalCost', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'movements', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'clients', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'tasks', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'commercialValue', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'totalCostTask', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'totalCostInventory', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'process'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'contractNumber', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'registrationDate', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'startDate', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'endTime', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'advances', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'totalCost', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'movements', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'clients', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'tasks', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'commercialValue', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'totalCostTask', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'totalCostInventory', '' . "\0" . 'App\\Entity\\Project' . "\0" . 'process'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Project $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getContractNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractNumber', []);

        return parent::getContractNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractNumber(?string $contractNumber): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractNumber', [$contractNumber]);

        return parent::setContractNumber($contractNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationDate', []);

        return parent::getRegistrationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationDate(\DateTimeInterface $registrationDate): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationDate', [$registrationDate]);

        return parent::setRegistrationDate($registrationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate(?\DateTimeInterface $startDate): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$startDate]);

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndTime(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndTime', []);

        return parent::getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndTime(?\DateTimeInterface $endTime): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndTime', [$endTime]);

        return parent::setEndTime($endTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdvances(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdvances', []);

        return parent::getAdvances();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdvances(?float $advances): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdvances', [$advances]);

        return parent::setAdvances($advances);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCost(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCost', []);

        return parent::getTotalCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCost(?float $totalCost): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCost', [$totalCost]);

        return parent::setTotalCost($totalCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovements', []);

        return parent::getMovements();
    }

    /**
     * {@inheritDoc}
     */
    public function addMovement(\App\Entity\Movement $movement): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMovement', [$movement]);

        return parent::addMovement($movement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMovement(\App\Entity\Movement $movement): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMovement', [$movement]);

        return parent::removeMovement($movement);
    }

    /**
     * {@inheritDoc}
     */
    public function getClients(): ?\App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClients', []);

        return parent::getClients();
    }

    /**
     * {@inheritDoc}
     */
    public function setClients(?\App\Entity\Client $clients): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClients', [$clients]);

        return parent::setClients($clients);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\User $user): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\User $user): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getTasks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTasks', []);

        return parent::getTasks();
    }

    /**
     * {@inheritDoc}
     */
    public function addTask(\App\Entity\Task $task): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTask', [$task]);

        return parent::addTask($task);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTask(\App\Entity\Task $task): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTask', [$task]);

        return parent::removeTask($task);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommercialValue(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommercialValue', []);

        return parent::getCommercialValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommercialValue(?float $commercialValue): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommercialValue', [$commercialValue]);

        return parent::setCommercialValue($commercialValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCostTask(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCostTask', []);

        return parent::getTotalCostTask();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCostTask(?float $totalCostTask): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCostTask', [$totalCostTask]);

        return parent::setTotalCostTask($totalCostTask);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCostInventory(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCostInventory', []);

        return parent::getTotalCostInventory();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCostInventory(?float $totalCostInventory): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCostInventory', [$totalCostInventory]);

        return parent::setTotalCostInventory($totalCostInventory);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcess(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcess', []);

        return parent::getProcess();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcess(?string $process): \App\Entity\Project
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcess', [$process]);

        return parent::setProcess($process);
    }

}
